coverage:
  range: 0..100
  round: down
  precision: 2
  status:
    project:
      default: false  # disable the default status that measures entire project
      source:
        paths:
          - "gradio/"
        target: 80%
        threshold: 0.1
    patch: off
  
comment: false
codecov:
  require_ci_to_pass: yes
